# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer
import os
from pathlib import Path
from tkinter import Tk, Canvas, Entry, Button, PhotoImage
from tkinter import messagebox
from AlmaIntegral.Modelo.Users import UserManagement
from AlmaIntegral.Vista.build_menu.build.menu import Menu


# from tkinter import *
# Explicit imports to satisfy Flake8

CURRENT_PATH = Path(__file__).parent
ASSETS_PATH = CURRENT_PATH / "build" / "assets" / "frame0"


def relative_to_assets(path: str) -> str:
    return os.path.join(ASSETS_PATH, path)


class Login:

    def __init__(self):
        self.user_management = UserManagement("../../assets/Inventory.db")
        self.menu = Menu(self)

        self.canvas = None
        self.window = None

        self.button_image_1 = None

        self.entry_image_1 = None
        self.entry_image_2 = None

        self.image_image_1 = None
        self.image_image_2 = None

        self.email_data = None
        self.password_data = None

        self.email_actual = None
        self.pass_actual = None

    def crear_ventana(self):
        self.window = Tk()
        self.window.geometry("360x800")
        self.window.configure(bg="#59A76E")

    def configurar_canvas(self):
        self.canvas = Canvas(
            self.window,
            bg="#59A76E",
            height=800,
            width=360,
            bd=0,
            highlightthickness=0,
            relief="ridge"
        )
        self.canvas.place(x=0, y=0)

        self.canvas.create_rectangle(
            0.0,
            615.0,
            360.0,
            738.0,
            fill="#59A76E",
            outline="")

        self.canvas.create_rectangle(
            0.0,
            0.0,
            360.0,
            719.0,
            fill="#FFFFFF",
            outline="")

    def boton_login(self):
        self.button_image_1 = PhotoImage(
            file=relative_to_assets("button_1.png"))
        boton_login = Button(
            image=self.button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=self.obtener_data,
            relief="flat"
        )
        boton_login.place(
            x=27.0,
            y=461.0,
            width=312.0,
            height=104.0
        )

    def password_field(self):
        self.canvas.create_text(
            145.0,
            380.0,
            anchor="nw",
            text="PASSWORD",
            fill="#000000",
            font=("Inter", 12 * -1)
        )

        self.canvas.create_rectangle(
            46.0,
            379.0,
            313.0,
            380.0,
            fill="#000000",
            outline="")

        self.entry_image_1 = PhotoImage(
            file=relative_to_assets("entry_1.png"))

        entry_bg_1 = self.canvas.create_image(
            195.0,
            359.5,
            image=self.entry_image_1
        )
        self.password_data = Entry(
            bd=0,
            bg="#FFFFFF",
            fg="#000716",
            highlightthickness=0
        )
        self.password_data.place(
            x=84.0,
            y=342.0,
            width=222.0,
            height=33.0
        )

        self.image_image_1 = PhotoImage(
            file=relative_to_assets("image_1.png"))

        image_1 = self.canvas.create_image(
            59.0,
            360.0,
            image=self.image_image_1
        )

    def email_field(self):
        self.canvas.create_text(
            145.0,
            305.0,
            anchor="nw",
            text="EMAIL ID",
            fill="#000000",
            font=("Inter", 12 * -1)
        )

        self.canvas.create_rectangle(
            46.0,
            304.0,
            313.0,
            305.0,
            fill="#000000",
            outline="")

        self.entry_image_2 = PhotoImage(
            file=relative_to_assets("entry_2.png"))
        entry_bg_2 = self.canvas.create_image(
            195.0,
            282.5,
            image=self.entry_image_2
        )
        self.email_data = Entry(
            bd=0,
            bg="#FFFFFF",
            fg="#000716",
            highlightthickness=0
        )
        self.email_data.place(
            x=84.0,
            y=265.0,
            width=222.0,
            height=33.0
        )

        self.image_image_2 = PhotoImage(
            file=relative_to_assets("image_2.png"))

        image_2 = self.canvas.create_image(
            59.0,
            286.0,
            image=self.image_image_2
        )

    def logo(self):
        self.canvas.create_text(
            119.0,
            126.0,
            anchor="nw",
            text="LOGIN",
            fill="#000000",
            font=("Inter", 25 * -1)
        )

    def iniciar_ventana(self):
        self.window.resizable(False, False)
        self.window.mainloop()

    def obtener_datos_email(self):
        if self.email_data.get():
            self.email_actual = self.email_data.get()
        else:
            messagebox.showerror("Error", "El campo de correo electrónico está vacío")

    def obtener_datos_password(self):
        if self.password_data.get():
            self.pass_actual = self.password_data.get()
        else:
            messagebox.showerror("Error", "El campo de contraseña está vacío")

    def obtener_data(self):
        self.obtener_datos_email()
        self.obtener_datos_password()
        if self.user_management.verify_credential(self.email_actual, self.pass_actual):
            self.correct_credential()
        else:
            messagebox.showerror("Error", "Usuario o contraseñan incorrectos")
        result = self.user_management.verify_credential(self.email_actual, self.pass_actual)
        print("login: ", result)

    def correct_credential(self):
        self.window.destroy()
        self.menu.start_menu()

    @staticmethod
    def iniciar_login():
        login = Login()
        login.crear_ventana()
        login.configurar_canvas()
        login.boton_login()
        login.password_field()
        login.email_field()
        login.logo()
        login.iniciar_ventana()


ventana = Login()
ventana.iniciar_login()
